spring:
  datasource:
    url: jdbc:h2:mem:lima2025
    driver-class-name: org.h2.Driver
    username: lima2025
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
